### PR TITLE
Add back interaction

### PR DESCRIPTION
**Pull request by hcorson-dosch**
This PR adds back in the chart interaction, with the goal of providing the name of the feature, its type (pool/flux/example), its volume/rate, an image and a definition. We may later also add in a link to WSS page, if available.

##### Initial plan:
Have a tooltip div that would be in a fixed location and would be populated and updated as you moused over the chart elements. 

As I started to implement this I realized it would be pretty tedious to get it to fit on the page in a good position at all page sizes, and with varying amounts of content (e.g. definitions of different lengths, image or no image).

##### Adapted implementation:

I realized what might be best was using a card that would pop up and then could be closed. I found a [youTube tutorial for creating dialogs in Vue](https://www.youtube.com/watch?v=hmvxqXUS-BU), and figured if I could get a button set up so that it launched a dialog box within 20 minutes then I'd go ahead and see if I could get it to work for the interaction. The tutorial was great and it ended up being pretty straightforward to set up a dialog Vue component and then set up a function to customize the dialog card. I think this will be really easy to adapt and use for other projects.

The interaction is triggered when you click on fully transparent rectangles that span the full width of the chart (including y-axis labels).

It looks like this:
PoolsFluxesCard

##### Not yet addressed
* There needs to be some indication (visual or a text prompt) that the user can click on the chart elements to pull up additional information
* Not all of the features have definitions currently - I only pasted in the first few
* Not all of the features have images
* The card needs to be styled

### CODE REVIEW

**Review by ceenell — APPROVED** [review]
smart solution. definitely agree it needs some sort of visual cue that it can be clicked on. 

How are you envisioning the layout and functionality on mobile? That seems important to address now that the main components are all here.

**Comment by hcorson-dosch** [comment]
> How are you envisioning the layout and functionality on mobile? That seems important to address now that the main components are all here.

Yes, mobile gets tricky. From an interaction standpoint I think the pop-up card works well on mobile - better even than a mouseover div would. I think the chart layout is more challenging. As is, the y-axis labels take up a bunch of the space, and the x-axis is pretty illegible :/

image

We could attempt something like this (but styled better):
image


I did chat w/ Elmera, Althea and Mandy a bit, and we figured that in school (but perhaps not outside of school) students would primarily be using tablets or laptops, so that may lower the importance of getting the mobile view perfect, at least for the MVP.

**Comment by ceenell** [comment]
I like this adding the text to the chart directly to save space. I'm assuming this is mobile in browser view? It would be worth checking out to see how the text sizing ends up. If the chart takes the full screen then clicking to get a pop-up could make it hard to scroll, but at the same time, we don't really need anything other than the chart.

**Comment by hcorson-dosch** [comment]
Yup this is just mobile in browser view -so might not be accurate. I am curious if it would be easy to inadvertently trigger a 'click' event when scrolling, or if the screens are calibrated to distinguish between those movements pretty well.

**Pull request merged**
