### PR TITLE
Add accessibility tags

### PR DESCRIPTION
**Pull request by hcorson-dosch**
This PR makes a number of changes to try to make the site more accessible, both for screenreaders and keyboard navigation. I looked at the current site on my iPhone and used the Voiceover option to see how the current page was read before making changes. It will probably make sense to test this once it's pushed to beta. 

The PR
* Adds titles to the d3 circles and range bands (not sure if these will be read or not)
  * per [Observable d3 accessibility notebook](https://observablehq.com/@9a849ed5a351d187/adventures-in-d3-accessibility)
  * Could also make these navigable w/ tab if they _aren't_ read, to see if that makes them readable
* Adds titles to the interaction rectangles (also visible on long mouseover) and makes them navigable w/ tab, w/ an event listener that opens the dialog on 'Enter'
* Allows the user to close the dialog w/ 'Esc' once the dialog is clicked on (see ToDo, below - eventually the click shouldn't be necessary)
* Adjust the order in which elements are added so that axis label is added (and therefore read) before the axis
* Drops empty elements previously created by d3
* Adds note to alt text that each image is a link and shortens alt text to 140 characters
* Uses semantic html where logical
* Adds aria roles, labels, and attributes to html elements (not certain these are right, but I tried to add them based on what I read to be correct)
  * [Aria docs](https://www.w3.org/TR/wai-aria/#roles)
  * [Mozilla Aria documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles)
  * [Getting started with Vue accessibility article](https://medium.com/@emilymears/getting-started-with-web-accessibility-in-vue-17e2c4ea0842)

ToDo:

1. Get the focus to switch to the Dialog when it is open, so that the user can use keyboard navigation within the dialog. 

* Definitely important for accessibility, per [Getting started with Vue accessibility article](https://medium.com/@emilymears/getting-started-with-web-accessibility-in-vue-17e2c4ea0842)
* Briefly explored a few things per [this](https://www.deque.com/blog/a-vue-of-accessibility-tips-and-tricks-to-make-your-application-accessible/), [this](https://www.telerik.com/blogs/how-to-trap-focus-modal-vue-3), and [this](https://vueuse.org/integrations/usefocustrap/), but they didn't work and I didn't dig further b/c I wanted to get the other changes up. I think the key is the 'ref' piece and triggering focus when the dialog is opened.

1. Test and make modifications, as needed. I'm not sure how the d3 titles will be handled.

### CODE REVIEW

**Comment by ceenell** [comment]
It would be super valuable for you to start documenting what you've learned here and the resources used in our documents, even if there is more to sort out. Let's also plan on using viz tools time in the next month to try this out with screen readers, in addition to @aaarchmiller' s drought page.

**Review by ceenell — APPROVED** [review]
These changes look really good and are a great step forward for us. 

I opened the test site using a chrome extension screen reader and noted that the main text at the top wasn't read. It read the USGS banner and then went between links and the `without ranges` and `log` buttons before getting into the chart. It also skipped over "Global pools", which might be useful to have read before the data. The tab navigation worked really well outside of that skipping.

Not sure what the best practice would be here, but it might make sense to eliminate the log/linear buttons altogether for screen readers, since the values stay the same regardless of the scale and this will be missed. That does eliminate other pieces of the page (like text at the bottom) for those users though, and I wonder if that is appropriate since it is a main aspect of the site. Same comment for the ranges.

Looks good to merge, but first look into whether it is simple to add the main text to the tab navigation to make sure that is captured.

**Comment by hcorson-dosch** [comment]
> I opened the test site using a chrome extension screen reader and noted that the main text at the top wasn't read. It read the USGS banner and then went between links and the `without ranges` and `log` buttons before getting into the chart. It also skipped over "Global pools", which might be useful to have read before the data. The tab navigation worked really well outside of that skipping.

You're right -- so weird! when tested the live site on my phone and using windows Narrator, that text was read, so something about how I set things up must have switched it. I'll make some tweaks now to fix that.

**Comment by hcorson-dosch** [comment]
> Not sure what the best practice would be here, but it might make sense to eliminate the log/linear buttons altogether for screen readers, since the values stay the same regardless of the scale and this will be missed. That does eliminate other pieces of the page (like text at the bottom) for those users though, and I wonder if that is appropriate since it is a main aspect of the site. Same comment for the ranges.

Yeah, I've been wondering about it. I'm leaning toward leaving as is, to allow full page function _and_ screen reader capacity for low-vision users, who might still be using those buttons while using a screen reader.

**Comment by hcorson-dosch** [comment]
Ok I've made edits to adjust how the site text is read, and will go ahead and merge.

I first used 'tabindex' in a lot of places to do so, and then decided this was *not* the correct approach, since it seems [the 'tab' key is used by screen readers to move between focusable items link links and buttons](https://dequeuniversity.com/screenreaders/survival-guide). I _think_ Chrome screenreader extension may be anomaly in that you can't use arrow keys to navigate the text, but instead have to click? Based on articles [like this](https://www.linkedin.com/pulse/screen-reader-navigation-vs-keyboard-girijesh-tripathi) I think ideally the only focusable items (buttons, links, menus, dialogs, etc.) are tab navigable, and the screen reader reads everything else based on up and down arrows or other screenreader navigation shortcuts. That's how I've attempted to set it up now.

I've also hidden the first bit of the chart title and the axis explanation from the screen reader.

Really interesting that different screen readers (e.g. Chrome extension vs. Windows narrator) read the site differently. I'll be interested to see how the iOS screen reader reads the beta site.

**Pull request merged**
