### PR TITLE
rewire pipeline to push images to s3 

### PR DESCRIPTION
**Pull request by ceenell**
- modifies existing pipeline to drop use of `dssecrets` for credentials in aws
- streamlines initial data steps so that there is only a single file read in via `public/data` that can be manually edited, which contains labels, volumes, image file paths, definitions, image credits etc. Moving forward, only this file should be edited.
- update page authorship 

To be able to run this pipeline you'll need to have aws credentials set up to access the `water-visualizations-prod-website` bucket. Then you 'll have to download the `Images` folder from the VizLab sharepoint (Vizlab/Projects/Water Cycle Diagram/) and place it in the root folder.

image

### CODE REVIEW

**Comment by ceenell** [comment]
Pinging @hcorson-dosch for awareness and @lindsayplatt for review

**Comment by ceenell** [comment]
Note: I made some modifications so that the `in` data are read in from `public/data/pools-fluxes-examples-limited.csv` for now so that it can be worked on without aws access. This makes the first few steps of the pipeline strange - reading in and saving the same csv, but will make sense when there is an `xlsx` file that gets manually edited in place of `'public/data/pools-fluxes-examples-limited.csv'`

**Review by lindsayplatt — APPROVED** [review]
Approving because new pipeline code looks good, even though I hit snags (see below) in the build!

I can build everything except `image_upload_s3` and `water_volume_s3` because my `saml2aws` setup isn't working properly in this repo (I keep getting an error about not using the appropriate endpoint, which I think has to do with the region? Changing the region doesn't seem to help).

Also tried building the website with `npm run serve`, but there are a bunch of failed installs for me, so I can't do that either :(

**Comment by ceenell** [comment]
The region should be west-2. Merging and will work with Hayley yo ensure everything is building as expected

**Review by hcorson-dosch — COMMENTED** [review]
This looks good, Cee. It all ran fine once I had everything set up locally.

**Comment by ceenell** [comment]
awwww yea!! 🥳

**Pull request merged**
